name: truecommand

services:
  truecommand:
    container_name: truecommand
    image: ixsystems/truecommand:latest
    restart: unless-stopped
    ports:
      - 42080:80
      - 42443:443
    volumes:
      - /home/ubuntu/docker/truecommand:/data
